services:
  domainnames-mongo:
    container_name: domainnames-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  domainnames-mongo-express:
    container_name: domainnames-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@domainnames-mongo:27017/

  domainnames-api:
    container_name: domainnames-api
    image: domainnames
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORTS=5000
      - Logging__Loglevel__Default=Debug
      - Logging__Loglevel__Microsoft.AspNetCore=Debug
      - CONNECTION_STRING=mongodb://root:example@domainnames-mongo:27017/
      - DATABASE_NAME=Domainnames_db
      - COLLECTION_NAME=Domainnames_collection
    ports:
      - "5000:5000"      
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro